version: '3.9'

services:
  heart-api:
    image: 'node:lts-alpine'
    working_dir: /home/node/app/dist
    ports:
      - '443:443'
    restart: always
    volumes:
      - './dist:/home/node/app/dist'
    command: sh -c "npm run start:docker"
    deploy:
      resources:
        limits:
          memory: 250M
