version: "3.8"

services:
  heart-api:
    image: "node:alpine"
    working_dir: /home/node/app
    ports:
      - "443:443"
    restart: always
    volumes:
      - "./package.json:/home/node/app/package.json"
      - "./.env-cmdrc.json:/home/node/app/.env-cmdrc.json"
      - "./dist:/home/node/app/dist"
      - "./certs:/home/node/app/certs"
    command: sh -c "npm install --global env-cmd && npm install && npm run docker-start-dev"
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 80M