version: '3.8'

services:
  heart-api:
    image: 'node:20-alpine'
    working_dir: /home/node/app/dist
    ports:
      - '443:443'
    restart: always
    volumes:
      - './dist:/home/node/app/dist'
    command: sh -c "npm run docker-start"
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 200M
